- name: Install unzip (Debian/Ubuntu)
  ansible.builtin.apt:
    name: unzip
    state: present

- name: Download Terraform
  get_url:
    url: https://releases.hashicorp.com/terraform/1.0.0/terraform_1.0.0_linux_amd64.zip
    dest: /tmp/terraform.zip

- name: Unzip Terraform
  ansible.builtin.unarchive:
    src: /tmp/terraform.zip
    dest: /usr/local/bin/
    remote_src: yes
    creates: /usr/local/bin/terraform
